[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# (optional) long-cache your mp3s
[[headers]]
  for = "/audio/tracks/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
